CREATE TABLE ItemsInOrder (
    OrderID VARCHAR(255) NOT NULL,
    ItemID VARCHAR(255) NOT NULL,
    StockID VARCHAR(255) NOT NULL,
    BookstoreID VARCHAR(255) NOT NULL,
    PubID VARCHAR(255) NOT NULL,
    DeliveryDatetime DATETIME,
    ItemPrice DECIMAL(18,2) NOT NULL,
    ItemQty INT NOT NULL,
    CustomerID VARCHAR(255) NOT NULL,
    OrderDatetime DATETIME NOT NULL, 
    Comment VARCHAR(255),
    Rating INT,

    PRIMARY KEY (ItemID, StockID, OrderID, BookstoreID, PubID),
    FOREIGN KEY (StockID, BookstoreID, PubID) REFERENCES StocksInBookstore(StockID, BookstoreID, PubID),
    FOREIGN KEY (OrderID) REFERENCES Orders(OrderID),
    FOREIGN KEY (BookstoreID) REFERENCES Bookstore(BookstoreID),
    FOREIGN KEY (PubId) REFERENCES Publications(PubId),
    FOREIGN KEY (CustomerID) REFERENCES Customers(CustomerID),
)